In [1]:
5+90

95

In [2]:
7%2

1

In [3]:
7%4

3

In [4]:
9**2

81

In [5]:
import numpy as np

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
import pandas as pd

pd.DataFrame({
    'nama' : ['Arief','Nauvan','Ramadha'],
    'umur' : [10,11,12],
    'provinsi' : ['Nganjuk', 'Kediri', 'Malang']
})

nama  umur provinsi
0    Arief    10  Nganjuk
1   Nauvan    11   Kediri
2  Ramadha    12   Malang

In [14]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()
print(digits.data)
digits.target
digits.images[0]

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [15]:
#ini adalah komentar

In [1]:
nama = 'Arief Nauvan Ramadha | TI-2G'
print(nama.upper())

ARIEF NAUVAN RAMADHA | TI-2G
